# This is a basic workflow to help you get started with Actions

name: tweet

# Controls when the action will run. 
on:
  schedule:
    - cron: 10 * * * *
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tweet"
  tweet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install tweepy
        run: pip install tweepy
        
      - name: Run the script
        run: plnp.py
        shell: python
        env:
          CONSUMERKEY: ${{ secrets.CONSUMERKEY }}
          CONSUMERSECRET: ${{ secrets.CONSUMERSECRET }}
          ACCESSTOKEN: ${{ secrets.ACCESSTOKEN }}
          ACCESSSECRET: ${{ secrets.ACCESSSECRET }}
